Update bq-redeploy.yml

diff --git a/.github/workflows/bq-redeploy.yml b/.github/workflows/bq-redeploy.yml
--- a/.github/workflows/bq-redeploy.yml
+++ b/.github/workflows/bq-redeploy.yml
@@ -30,7 +30,14 @@ jobs:
         run: |
           file="bq/query.sql"
 
-          query_validation=$(bq query --use_legacy_sql=false --dry_run --format=csv "SELECT 1" ); is_valid=$?; echo "$is_valid"
+          query_validation=$(bq query --use_legacy_sql=false --dry_run --format=csv "SELECT 1" 2>&1)
           
+          if [[ $? -ne 0 ]]; then
+            echo "BigQuery Query Validation Failed:"
+            echo "$query_validation"
+            exit 0 # exit 0 to prevent workflow failure
+          else
+             echo "BigQuery Query Validation Succeeded"
+          fi
 
           
