Update bq-redeploy.yml

diff --git a/.github/workflows/bq-redeploy.yml b/.github/workflows/bq-redeploy.yml
--- a/.github/workflows/bq-redeploy.yml
+++ b/.github/workflows/bq-redeploy.yml
@@ -30,17 +30,18 @@ jobs:
         run: |
           file="bq/query.sql"
 
-          bq query --use_legacy_sql=false --dry_run --format=csv "SELECT 1"
           
-          echo "entro"
           query_validation=$(bq query --use_legacy_sql=false --dry_run --format=csv "SELECT 1")
-          echo "$query_validation"
-          echo "No corrio"
+          is_valid=$?
 
           
-          if [[ "$query_validation" =~ ^[0-9]+$ ]]; then
-            echo "It works"
+          if [[ "$is_valid" -eq 0 ]]; then
+            if [[ "$query_validation" =~ ^[0-9]+$ ]]; then
+              echo "It works"
+            else
+              echo "Validation Error: $file: $query_validation"
+            fi
           else
-            echo "$file: $query_validation"
-            exit 1
+            echo "Error: $query_validation"
           fi
+          
