Update connect-gcp.yml

diff --git a/.github/workflows/connect-gcp.yml b/.github/workflows/connect-gcp.yml
--- a/.github/workflows/connect-gcp.yml
+++ b/.github/workflows/connect-gcp.yml
@@ -29,6 +29,18 @@ jobs:
       - name: Read buckets
         shell: bash
         run: | 
-          salida=$(gcloud composer environments run instance --location=us-central1 dags list-import-errors -- --output=json 2>&1 || true)
 
-          echo "La salida es: $salida"
+          compile_errors=$(gcloud composer environments run instance --location=us-central1 dags list-import-errors -- --output=json 2>&1 || true)
+          
+          json_output=$(echo "$compile_errors" | grep -o '\[.*\]$')
+          
+          transformed_json=$(echo "$json_output" | jq -r '
+            map({
+              (.filepath | split("/") | last | split(".")[0]): .error
+            }) | add
+          ')
+          
+          users_value=$(echo "$transformed_json" | jq -r '.users')
+          
+          
+          echo "$users_value"
