Update gh-ci-deploy-workflow.yml

diff --git a/.github/workflows/gh-ci-deploy-workflow.yml b/.github/workflows/gh-ci-deploy-workflow.yml
--- a/.github/workflows/gh-ci-deploy-workflow.yml
+++ b/.github/workflows/gh-ci-deploy-workflow.yml
@@ -148,17 +148,28 @@ jobs:
             done
           fi
 
-          echo "DAGs to update: ${found_dags[@]} " >> $GITHUB_STEP_SUMMARY
+          echo "DAGs to update: ${versioned_dags_to_deploy[@]} " >> $GITHUB_STEP_SUMMARY
           
-          #Eliminado
+          # Iterate through the array of found dags to add deploy-specific ID
+          if [[ ${#found_dags[@]} -gt 0 ]]; then
+              for found_dag in "${found_dags[@]}"; do
+                  versioned_dags_to_deploy+=("${DAG_ID_SUFFIX}")
+              done
+          else
+              echo "::error::No matching DAG files found. Review your repository files"
+              exit 1
+          fi
+
+          echo "DAGs will be deployed as:"
+          echo "${versioned_dags_to_deploy[@]}" # Space separated list
 
 
           # Create JSON string to update Airflow dags_version variable
           deploying_dags_json="{"
           for i in "${!found_dags[@]}"; do
             key="${found_dags[$i]}"
-            value="${{ steps.get-gitref.outputs.git_ref }}"
-            
+            value="${versioned_dags_to_deploy[$i]}"
+
             # Add comma separator (except for the last element)
             if [[ $i -lt $(( ${#found_dags[@]} - 1 )) ]]; then
               deploying_dags_json+="\"$key\":\"$value\","
@@ -170,4 +181,5 @@ jobs:
           
           deploy_dags_jq=$(echo "$deploying_dags_json" | jq -c '.') # Convert JSON string to jq-readable format       
 
-          echo "SALIDA: $deploying_dags_json"
+
+          echo "$deploy_dags_jq"
