Fix error message print in state_poll.yml

diff --git a/.github/workflows/state_poll.yml b/.github/workflows/state_poll.yml
--- a/.github/workflows/state_poll.yml
+++ b/.github/workflows/state_poll.yml
@@ -102,11 +102,11 @@ jobs:
               break
             fi
 
-            errors=$(gcloud composer environments run ${{ needs.review.outputs.composer_environment_name }} --location=${{ needs.review.outputs.region }} dags list-import-errors -- --output=json)
+            errors=$(gcloud composer environments run ${{ needs.review.outputs.composer_environment_name }} --location=${{ needs.review.outputs.region }} dags list-import-errors -- --output=json) || echo "$errors"
             is_empty=$(echo "$errors" | jq 'length')
 
             if [[ "$is_empty" -ne 0 ]]; then
-              echo "$errors"
+              echo "Found errors in Airflow DAGs."
               exit 1
             fi
             
