Update state_poll.yml

diff --git a/.github/workflows/state_poll.yml b/.github/workflows/state_poll.yml
--- a/.github/workflows/state_poll.yml
+++ b/.github/workflows/state_poll.yml
@@ -69,3 +69,46 @@ jobs:
         run: | 
           gcloud storage cp "${{ steps.get-change.outputs.dag_change }}" ${{ needs.review.outputs.composer_gcs_bucket }}/${{ steps.get-change.outputs.dag_name }}/dags/
 
+      - name: Check DAGs Composer
+        if: steps.changed-files.outputs.any_changed
+        run: |
+          POLL_PERIOD=5           # Poll every minute
+          WHILE_TIMEOUT=$((60*15)) # 15 minutes
+          ELAPSED=0                # Runtime
+
+          deployed_dags=${{ steps.get-change.outputs.dag_new_version }}
+
+          echo "$deployed_dags"
+
+          while true; do
+            
+            # Check for timeout
+            if [ "$ELAPSED" -ge "$WHILE_TIMEOUT" ]; then
+              echo "State polling timed out."
+              exit 1
+            fi
+
+            sleep $POLL_PERIOD
+            ELAPSED=$((ELAPSED + POLL_PERIOD))
+            
+            composer_dags=$(gcloud composer environments run ${{ needs.review.outputs.composer_environment_name }} --location=${{ needs.review.outputs.region }} dags list -- --output=json | jq "[.[] | select(.dag_id == \"$deployed_dags\")] | length ")
+            
+            if [[ "$composer_dags" -eq 0 ]]; then
+              errors=$(gcloud composer environments run ${{ needs.review.outputs.composer_environment_name }} --location=${{ needs.review.outputs.region }} dags list-import-errors -- --output=json)
+
+              echo "$errors"
+              
+              if [[ -z "$errors" ]]; then
+                echo "No import errors found. Continuing loop."
+              else
+                echo "Import errors found:"
+                echo "$errors"
+                echo "Send error ...."
+                break
+              fi
+            else
+              echo "DAG match. Exiting."
+              break
+            fi
+            
+          done
